version: '3.4'

services:

  bankservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "52598:80"
      - "44381:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  newsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "52691:80"
      - "44306:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
      
  weatherservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50810:80"
      - "44384:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  worldnewsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "60940:80"
      - "44357:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
