version: '3.4'

services:
  portal_2.0:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "54948:80"
      - "44334:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bankservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "52598:80"
      - "44381:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  newsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "52691:80"
      - "44306:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  weatherservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50810:80"
      - "44384:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  worldnewsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "60940:80"
      - "44357:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
